Iter15: new delete handler
AvdeevK/url-cutter pull request #16
Opened 2024-12-02 21:42 UTC by AvdeevK

2024-12-03 05:14 UTC, bulbetski requested changes

2024-12-03 05:14 UTC, bulbetski commented on internal/auth/auth.go
> +const tokenExp = time.Hour * 3
стоит синхронизировать время жизни токена и время жизни куки. Таким образом избежим ситуация, когда клиент может отправить устаревший токен в запросеи избежим лишней нагрузки на сервер для обработки недействительного токена

2024-12-03 05:14 UTC, bulbetski commented on internal/auth/auth.go
> +const tokenExp = time.Hour * 3
так же нужно добавить явную проверку на протухание токена

2024-12-03 05:14 UTC, bulbetski commented on internal/auth/auth.go
> +const secretKey = "supersecretkey"
секретный ключ надо брать из переменной среды

2024-12-03 05:14 UTC, bulbetski commented on internal/handlers/handlers.go
>  	CREATE UNIQUE INDEX IF NOT EXISTS unique_original_url ON urls (original_url);
Рассмотри использование механизма миграций. Самый популярный: https://github.com/pressly/goose

Это позволит легко менять схему данных, поддерживать версионирование. Также над проектом потенциально смогут работать несколько разрабов без риска похерить данные и заработать конфликт

2024-12-03 05:14 UTC, bulbetski commented on internal/handlers/handlers.go
>  		w.WriteHeader(http.StatusBadRequest)
Более уместе 405 Method Not Allowed

2024-12-03 05:14 UTC, bulbetski commented on internal/handlers/handlers.go
> +	userID, exists, err := auth.GetAuthCookie(r)
Логика работы с куками (GetAuthCookie, SetAuthCookie, GenerateUserID) интегрирована в обработчик, что нарушает принцип единственной ответственности. Нужно вынести логику аутентификации в middleware или отдельную функцию

2024-12-03 05:14 UTC, bulbetski commented on internal/handlers/handlers.go
>  		if err.Error() == "conflict" {
стоит сделать кастомную ошибку и сравнивать через errors.Is

2024-12-03 05:14 UTC, bulbetski commented on internal/handlers/handlers.go
> +	}
Здесь куки повторно устанавливаются, даже если они были успешно созданы или обновлены ранее

2024-12-03 05:14 UTC, bulbetski commented on internal/handlers/handlers.go
К этому методу аналогичные замечания

2024-12-03 05:14 UTC, bulbetski commented on internal/handlers/handlers.go
> +	originalURL, isDeleted, err := store.GetOriginalURL(shortURL)
можно объединить в какую-нибудь структуру

2024-12-03 05:14 UTC, bulbetski commented on internal/storage/file_storage.go
>  	lastUUID += 1
В бд можно сделать айдишник автоинкрементом, он будет сам увеличиваться и его не придется каждый раз вставлять

2024-12-03 05:14 UTC, bulbetski commented on internal/storage/file_storage.go
> +	attributes, exists := f.urls[shortURL]
В нашем memory storage (в map) мы можем хранить структуры и там тоже можно и нужно прописать удаленная ли запись или нет

2024-12-03 05:14 UTC, bulbetski commented on internal/storage/file_storage.go
> +	return originalURL, false, nil
соотвественно вот здесь надо будет возвращать актуальное состояние записи (удалено или нет)

2024-12-03 05:14 UTC, bulbetski commented on internal/storage/file_storage.go
> +		attributes := &[]string{record.OriginalURL, record.UserID}
можно убрать ссылку и тогда дальшне не придется разыменовывать указатель

2024-12-03 05:14 UTC, bulbetski commented on internal/storage/file_storage.go
> +	attributes := &[]string{newURL.OriginalURL, newURL.UserID}
можно убрать ссылку и тогда дальшне не придется разыменовывать указатель

2024-12-03 05:14 UTC, bulbetski commented on internal/storage/memory_storage.go
> +	urls        map[string][]string
Можно массив строк заменить на кастомную структуру, тогда сможем в 1 записи хранить все необходимые поля

2024-12-03 05:14 UTC, bulbetski commented on internal/storage/file_storage.go
> +	attributes := &[]string{newURL.OriginalURL, newURL.UserID}
или можно просто сразу сделать f.urls[newURL.ShortURL] = []string{newURL.OriginalURL, newURL.UserID}

2024-12-03 05:14 UTC, bulbetski commented on internal/storage/postgres_storage.go
>          RETURNING short_url;
DO NOTHING RETURNING ничего не вернет, вот такой вот прикол. Все когда-то на него попадаются.
Нужно сделать вот так
```
ON CONFLICT
DO UPDATE SET
    short_url=EXCLUDED.short_url
RETURNING short_url;
```

2024-12-03 05:14 UTC, bulbetski commented on internal/storage/postgres_storage.go
>  		if err == sql.ErrNoRows {
sql.ErrNoRows не может возникнуть в запросе с Returning, можно удалить проверку

2024-12-03 05:14 UTC, bulbetski commented on internal/storage/postgres_storage.go
> +func (db *PostgresStorage) SaveBatchTransaction(
Раз мы хотим сохранять батч, то лучше сначала сгенерировать все данные и потом передать их массивом внутрь SaveBatch. Так же insert множества значений можно выполнить 1 операцией, тогда нам не нужна будет транзакция

2024-12-03 05:14 UTC, bulbetski commented on internal/storage/postgres_storage.go
> +	if err := rows.Err(); err != nil {
Проверка rows.Err() выполняется до вызова defer rows.Close(). Это может привести к утечке ресурсов, если ошибка произошла при создании rows, так как rows.Close() не будет вызван. Стоит переместить defer rows.Close() сразу после успешного вызова db.db.Query.

2024-12-08 22:03 UTC, AvdeevK commented on internal/storage/postgres_storage.go
>          RETURNING short_url;
Могу ошибаться, но в таком случае каждый раз обновляем просто короткий урл, будто бы снова его сокращаем для пользователя, а по заданию должны уметь 409 отдавать и уже имеющийся сокращенный урл:

`
При попытке пользователя сократить уже имеющийся в базе URL через хендлеры POST / и POST /api/shorten сервис должен вернуть HTTP-статус 409 Conflict, а в теле ответа — уже имеющийся сокращённый URL в правильном для хендлера формате.
`

2024-12-19 14:21 UTC, bulbetski commented on internal/handlers/handlers.go
> +		http.Error(w, "empty user id", http.StatusUnauthorized)
надо делать return после ошибок

2024-12-19 14:21 UTC, bulbetski commented on internal/handlers/handlers.go
>  		if err.Error() == "conflict" {
Не исправил, но не крит

2024-12-19 14:25 UTC, bulbetski commented on internal/storage/postgres_storage.go
>          RETURNING short_url;
В том-то и дело, что не обновляем. EXCLUDED.short_url это тот самый "старый" урл, который был до конфликта, его мы и возвращаем

2024-12-19 14:25 UTC, bulbetski commented on internal/storage/postgres_storage.go
>  		if err == sql.ErrNoRows {
не убрал проверку

2024-12-19 14:29 UTC, bulbetski approved these changes
Остались микро-комменты. Поправь их перед мерджем. В целом исправил всё небо и земля, оч хороший код получился

2024-12-19 14:29 UTC, bulbetski commented on internal/storage/postgres_storage.go
> +	return nil
ты оставил цикл for, но убрал транзакцию. Это неправильно. В таком случае транзакция всё же нужна.
Она была бы не нужна, если бы сделали множественный insert
INSERT INTO urls (user_id, short_url, original_url) VALUES ($1, $2, $3) ($4, $5, $6) итд

Вот эту строку `($1, $2, $3) ($4, $5, $6)` можно генерировать при помощи хелпера

2024-12-22 11:54 UTC, merged